//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemusixApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int UserID { get; set; }
        public int nUserID { get; set; }
        public Nullable<int> PostID { get; set; }
        public string Action { get; set; }
        public System.DateTime ActionTime { get; set; }
        public string Status { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
