//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemusixApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFollowArtist
    {
        public int UserID { get; set; }
        public int ArtistID { get; set; }
        public string empty { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual User User { get; set; }
    }
}
